version: '2'

services:
    libdemodev:
        build:
            context: .
            dockerfile: dev.dockerfile
        volumes:
            - ".:/var/www"
        ports:
            - "3000:5000"
        networks:
            - library_net
    libdemo:
        build:
            context: .
            dockerfile: dockerfile
        ports: 
            - "5000:5000"
        networks: 
            - library_net

    mysqlserver:
        build:
            context: .
            dockerfile: mysql.dockerfile
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=LibraryDemo
        ports: 
            - "3306:3306"
        networks:
            - library_net
        volumes:
            - libraryDB:/var/lib/mysql

networks:
    library_net:
        driver: bridge

volumes:
    libraryDB:

